services:
  web:  # Django service (API)
    build: .
    command: bash -c "./wait-for-it.sh db:5432 && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=db+postgresql://admin:admin@db:5432/to_do_app
      - DATABASE_URL=postgresql://admin:admin@db:5432/to_do_app
      - SECRET_KEY=django-insecure-y3sq_^p+=6$a)f&h*1)x$3jp(t$$1l^&c54ho&af7z)7elfwor
      - DEBUG=True
      - BOT_TOKEN=7818772601:AAH6WQ0HzCK4pwGXiTmbnqDwDbnMHu__D7A  # Used by Django for JWT signing key
    networks:
      - mynetwork

  db:  # PostgreSQL database
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: to_do_app
    networks:
      - mynetwork

  redis:  # Redis service
    image: redis:7.2-alpine
    volumes:
      - redis_data:/data
    networks:
      - mynetwork

  celery_worker:  # Celery worker
    build: .
    command: celery -A to_do_app worker -l info
    volumes:
      - .:/code
    depends_on:
      - web
      - redis
      - db
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=db+postgresql://admin:admin@db:5432/to_do_app
      - DATABASE_URL=postgresql://admin:admin@db:5432/to_do_app
      - SECRET_KEY=django-insecure-y3sq_^p+=6$a)f&h*1)x$3jp(t$$1l^&c54ho&af7z)7elfwor
      - DEBUG=True
      - BOT_TOKEN=7818772601:AAH6WQ0HzCK4pwGXiTmbnqDwDbnMHu__D7A
    networks:
      - mynetwork

  bot:  # Telegram bot service
    build: .
    command: python -m bot.main
    volumes:
      - .:/code
    depends_on:
      - web
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=db+postgresql://admin:admin@db:5432/to_do_app
      - DATABASE_URL=postgresql://admin:admin@db:5432/to_do_app
      - SECRET_KEY=django-insecure-y3sq_^p+=6$a)f&h*1)x$3jp(t$$1l^&c54ho&af7z)7elfwor
      - DEBUG=True
      - BOT_TOKEN=7818772601:AAH6WQ0HzCK4pwGXiTmbnqDwDbnMHu__D7A
    networks:
      - mynetwork

volumes:
  postgres_data:
  redis_data:

networks:
  mynetwork:
    driver: bridge