# Generated by Django 5.1.7 on 2025-03-24 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='celery_task_id',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True),
        ),
    ]
