# Generated by Django 5.1.7 on 2025-03-24 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list', '0004_category_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='user_task_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
